name: Build Docker Image

on:
  push:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: "Docker"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get additional build args
        id: get_build_args
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "branch=latest" >> $GITHUB_OUTPUT
          else
            echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/minerpl/ryneczek:${{ steps.get_build_args.outputs.branch }}
            ghcr.io/minerpl/ryneczek:${{ steps.get_build_args.outputs.short_sha }}
